import UIKit

class Content {
    static let calories = [51, 46, 53, 65, 67, 55]
    
    static let titleEx = [["Squats","Balance","Lunges","Side Lying Hip Abduction"],
                          ["Crunch with one leg","Leg Crunch","Reverse Leg Crunch","Superman"],
                          ["Plank","Reverse Crunch","Movable plank","Lower crunch"],
                          ["Spider Lunge","Side Plank","Stand with one hand","Scissor Crunches"],
                          ["V legs","Stand with Single-leg Raise","Stand with Single-leg Raise","Push-Up","Crunch with one leg"],
                          ["Balance","Lunges","Side Lying Hip Abduction","Glute bridge"],
                          ]
    
    static let explanations = ["Four exercises for 5 minutes","Four exercises for 5 minutes","Four exercises for 5 minutes","Four exercises for 5 minutes","Five exercises for 7 minutes","Five exercises for 7 minutes","Today is rest day. Enjoy yourself!"]
    
    static let exDescription = ["It's no secret that strength training is a critical part of any weekly workout schedule. Lets start with legs our week","Step-by-step guide to train your stamina","Exercises that can help you increase your muscles and health","Middle of the week for good train guide to build our body","When it comes to training, you should aim to hit all of your major muscle groups","Step-by-step guide to train your legs and abs","But dont be very lazy"]
    
//    static let exDescription  = [["Position your feet somewhere between hip- and shoulder-width apart.","Keep your chest tall.","Shift your weight through your midfoot and heel.","Lie on your side with your legs extended straight away from your body. Hold your feet together in neutral position. Your hips and shoulder should be aligned vertically to the floor"],
//                                 ["One leg dont movable","Up your leg upper as musch as you can","Up your leg upper as musch as you can","Lie facedown on floor with arms in front of body, palms toward the ground. Draw navel in, tighten glutes, and pinch shoulder blades together. Simultaneously lift arms, chest, and legs off the floor. Hold. Slowly return to ground, keeping chin tucked."],
//                                 ["Lie facedown on the floor with feet together and forearms on the ground. Draw abs in and tighten glutes. Hold.","Lower back pressed to the ground. Extend hands out alongside body. Lift feet up.","Like plank, but now lift the pelvis up and lower","Move only your head and torso"],
//                                 ["Start in the top of a pushup position. Bring your right foot to the outside of your right hand.","Lie on side with lower arm bent at the elbow. Place lower elbow beneath shoulder and place upper hand on hip. Align ankles, hips, shoulders, and head.","Up your one hand in stand","Lie on back with feet together, legs extended, and hands behind head with elbows wide. Lift your legs alternately"],
//                                 ["Lie on your back and up legs aligned. Dont touch the floor","A great progression from a regular stand but remember to keep proper form.","A great progression from a regular stand but remember to keep proper form.","The Push-up is an oldie but goodie.  You can modify intensity by changing hand placement.","One leg dont movable"],
//                                 ["Keep your chest tall.","Shift your weight through your midfoot and heel.","Lie on your side on a mat/floor with your legs extended straight away from your body. Hold your feet together in neutral position. Your hips and shoulder should be aligned vertically to the floor. Your head should be aligned with your spine.","Contract your abdominal muscles and slowly lift your hips off floor so that your body forms a straight line from knees to shoulders. Squeeze your glutes tight, as you press your hips toward the ceiling. Hold for a beat, then lower slowly back down to the floor."],
//                                 ]
    
    static let dietDescription = ["     Breakfast (274 calories)\n\n Yogurt with Blueberries & Honey\n• 1 cup nonfat plain Greek yogurt\n• 1/2 cup blueberries\n• 1 tsp. honey\nTop yogurt with blueberries & honey.\n• 1 1/2 Tbsp. almonds on the side\n\n     A.M.Snack (90 calories)\n\n• 1/2 medium green bell pepper, sliced\n• 3 Tbsp. hummus\n\n     Lunch (330 calories)\n\nWhite Bean & Avocado Toast\n• 1 slice whole-wheat bread, toasted\n• 1/2 avocado, mashed\n• 1/4 cup white beans, mashed\n• Salt and pepper\nTop toast with avocado and white beans. Season with a pinch each of salt and pepper, and if desired, crushed red pepper.\n• 2 cups mixed greens dressed with 1 tsp. olive oil & 2 tsp. red-wine vinegar\n\n     P.M.Snack (48 calories)\n\n• 3/4 cup raspberries\n\n     Dinner (476 calories)\n\n• 1 serving Creamy Chicken & Mushrooms\n• 1 cup Balsamic-Parmesan Roasted Cauliflower\n\n    Daily Total: 1,218 calories, 78 g protein, 95 g carbohydrates, 31 g fiber, 64 g fat, 1,301 mg sodium\n",
                                  "     Breakfast (291 calories)\n\n• 1/2 cup rolled oats, cooked in 1 cup low-fat milk\n• 1/3 cup raspberries, fresh or frozen\n• 1 tsp. maple syrup\n• Pinch of cinnamon\nCook oats and top with raspberries, maple syrup and a pinch of cinnamon.\n\n     A.M.Snack (78 calories)\n\n• 1 hard-boiled egg\n• 1 tsp. hot sauce\nPeel egg and cut in half. Season with hot sauce and a pinch each of salt and pepper.\n\n     Lunch (354 calories)\n\n• 1 serving Apple & Cheddar Pita Pockets\n\n     P.M.Snack (25 calories)\n\nEasy Cucumber Salad\n• 1 1/2 cups sliced cucumber\n• 1 tsp. lemon juice\n• Salt, pepper & dried dill to taste\nToss cucumber with lemon juice, salt, pepper and dill.\n\n     Dinner (472 calories)\n\n• 1 serving Stuffed Sweet Potato with Hummus Dressing\nMake-Ahead Tip: Save 1/4 cup black beans to have for lunch on Day 4.\n\n     Daily Total: 1,220 calories, 56 g protein, 192 g carbohydrates, 37 g fiber, 29 g fat, 1,955 mg sodium\n",
                                  "     Breakfast (290 calories)\n\nPeanut-Butter Banana Toast\n• 1 slice whole-wheat bread, toasted\n• 1 Tbsp. peanut butter\n• 1 medium banana, sliced\nTop toast with peanut butter and banana.\n\n     A.M.Snack (102 calories)\n\nCinnamon Pears\n• 1 medium pear\n• 1 tsp. cinnamon\nSlice pear and sprinkle with cinnamon.\n\n     Lunch (340 calories)\n\n• 4 cups Fig & Goat Cheese Salad\n\n     P.M.Snack (32 calories)\n\n• 1/2 cup raspberries\n\n     Dinner (453 calories)\n\n• 1 serving Citrus Poached Salmon with Asparagus\n• 3/4 cup cooked quinoa seasoned with salt & pepper to taste\nServe salmon and asparagus over quinoa.\n• 1 Tbsp. dark chocolate chips, to enjoy after dinner.\n\n     Make-Ahead Tip: Save 1/2 cup quinoa to have for lunch on Day 4 and 1/2 cup to have for lunch on Day 6.\n\n     Daily Total: 1,217 calories, 52 g protein, 153 g carbohydrates, 30 g fiber, 48 g fat, 996 mg sodium",
                                  "     Breakfast (269 calories)\n\nGreek Yogurt with Fruit & Nuts\n• 1 cup nonfat plain Greek yogurt\n• 3 dried apricots, chopped\n• 2 Tbsp. chopped walnuts\n• 1 tsp. maple syrup\nTop yogurt with apricots, walnuts & maple syrup\n• 1 medium orange\n\n     A.M. Snack (90 calories)\n\n• 3 Tbsp. hummus\n• 1/2 green bell pepper, sliced\n\n     Lunch (338 calories)\n\nBlack Bean Quinoa Bowl with Hummus Dressing\n• 1/2 cup cooked quinoa\n• 1/4 cup black beans\n• 1/4 avocado, diced\n• 3 Tbsp. pico de gallo or salsa\n• 2 Tbsp. chopped cilantro\nTo make dressing: Combine 3 Tbsp. hummus with 1 Tbsp. each lime juice and warm water. Add more water, if needed, for the desired consistency.\nCombine quinoa, black beans, avocado, pico de gallo (or salsa) and cilantro in a bowl. Top with hummus dressing and, if desired, hot sauce.\n\n     P.M. Snack (95 calories)\n\nCinnamon Apples\n• 1 medium apple\n• 1 tsp. cinnamon\nSlice apple and sprinkle with cinnamon.\n\n     Dinner (414 calories)\n\n• 2 cups Balsamic Berry Vinaigrette Winter Salad\n• 5 oz. cooked chicken breast\nTop the salad with the chicken.\n\n     Daily Total: 1,206 calories, 92 g protein, 132 g carbohydrates, 28 g fiber, 39 g fat, 1,116 mg sodium\n",
                                  "     Breakfast (274 calories)\n\nYogurt with Blueberries & Honey\n• 1 cup nonfat plain Greek yogurt\n• 1/2 cup blueberries\n• 1 tsp. honey\nTop yogurt with blueberries & honey.\n• 1 1/2 Tbsp. almonds on the side\n\n     A.M. Snack (78 calories)\n\n• 1 hard-boiled egg\n• 1 tsp. hot sauce\nPeel egg and cut in half. Season with hot sauce and a pinch each of salt and pepper.\n\n     Lunch (355 calories)\n\nGreen Salad with Pita Bread & Hummus\n• 2 cups mixed greens\n• 1/2 cup sliced cucumber\n• 2 Tbsp. grated carrot\n• 2 tsp. balsamic vinegar\n• 1 tsp. olive oil\n• 1 6-inch whole-wheat pita bread, toasted\n• 1/4 cup hummus\nCombine greens, cucumber and carrot and toss with vinegar and oil. Season with a pinch each salt and pepper. Serve with the toasted pita bread and hummus.\n\n     P.M. Snack (69 calories)\n\n• 3/4 cup raspberries\n• 1/4 cup blueberries\n\n     Dinner (442 calories)\n\n• 1 serving Roasted Root Vegetables with Goat Cheese Polenta\nMake-Ahead Tip: Save 1 cup of roasted root vegetables to have for tomorrow's lunch.\n\n     Daily Total: 1,217 calories, 56 g protein, 139 g carbohydrate, 29 g fiber, 54 g fat, 1,765 mg sodium\n",
                                  "     Breakfast (286 calories)\n\n• 1/2 cup rolled oats, cooked in 1 cup low-fat milk\n• 1/4 cup raspberries, fresh or frozen\n• 1 tsp. maple syrup\n• Pinch of cinnamon\nCook oats and top with raspberries, maple syrup and cinnamon.\n\n     A.M. Snack (62 calories)\n\n• 1 medium orange\n\n     Lunch (351 calories)\n\n• 1 serving Roasted Veggie & Quinoa Salad\n\n     P.M. Snack (74 calories)\n\n• 1/4 cup blueberries\n• 2 tsp. dark chocolate chips\n\n     Dinner (450 calories)\n\n• 3 1/2 cups Vegetable Weight Loss Soup\n\n      Daily Total: 1,222 calories, 51 g protein, 168 g carbohydrates, 35 g fiber, 44 g fat, 1,302 mg sodium\n",
                                  "     Breakfast (262 calories)\n\n• 2 1/2 cups Baby Kale Breakfast Salad with Bacon & Egg\n\n     A.M. Snack (102 calories)\n\nCinnamon Pears\n• 1 medium pear\n• 1 tsp. cinnamon\nSlice pear and sprinkle with cinnamon.\n\n     Lunch (337 calories)\n\n• 2 cups Vegetable Weight Loss Soup\n\n     P.M. Snack (64 calories)\n\n• 1 cup raspberries\n\n     Dinner (456 calories)\n\n• 1 serving Charred Vegetable & Chicken Pita with Garlic Mayo\n\n     Daily Total: 1,222 calories, 64 g protein, 129 g carbohydrate, 32 g fiber, 56 g fat, 1,565 mg sodium\n"]
    static let caloriesDiet = ["Calories: 274","Calories: 291","Calories: 290","Calories: 269","Calories: 274","Calories: 286","Calories: 262"]
    
    static let dietImage = ["image0", "image1", "image2", "image3", "image4", "image5", "image6"]
    
    
    struct Workout {
        static let firstWorkout = ["0-0", "0-1" , "0-2", "0-3"]
        static let secondWorkout = ["5-0", "5-1" , "5-2", "5-3"]
        static let thirdWorkout = ["2-0", "2-1" , "2-2", "2-3"]
        static let fourthWorkout = ["3-0", "3-1" , "3-2", "3-3"]
        static let fifthWorkout = ["4-0", "4-1" , "4-2", "4-3", "4-4"]
        static let sixthWorkout = ["1-0", "1-1" , "1-2", "1-3"]
        static let seventhWorkout = [String]()
        
        static let workoutTitles = ["First Day", "Second Day", "Third Day", "Forth Day", "Fifth Day", "Sixth Day", "Seventh Day"]
        static let descriptionTexts = ["Start of week for legs","Day for Cardio","Upper body/Lower body","Day for Legs/Abs","Total-Body Strength Training","Abs/Legs training","End of week for Rest"]
        
        static let all = [firstWorkout,secondWorkout,thirdWorkout,fourthWorkout,fifthWorkout,sixthWorkout,seventhWorkout]
    }
}

